### ISSUE TITLE
Memory leak when idle

### ISSUE THREAD

**Issue by leovailati** [jonhoo/bus#11]
The following program will slowly leak memory until it exhausts my system's resources.

```rust
extern crate bus;
use bus::Bus;

use std::thread;
use std::time::Duration;

fn main() {
    let mut b: Bus<usize> = Bus::new(10);

    let mut rx1 = b.add_rx();
    let mut rx2 = b.add_rx();
    let mut rx3 = b.add_rx();
    let mut rx4 = b.add_rx();
    let mut rx5 = b.add_rx();
    let mut rx6 = b.add_rx();

    thread::spawn(move || for _ in rx1.iter() {});
    thread::spawn(move || for _ in rx2.iter() {});
    thread::spawn(move || for _ in rx3.iter() {});
    thread::spawn(move || for _ in rx4.iter() {});
    thread::spawn(move || for _ in rx5.iter() {});
    thread::spawn(move || for _ in rx6.iter() {});
    
    // UNCOMMENT FOLLOWING LINES TO SEE HOW USING
    // THE CHANNEL FREQUENTLY CAN MITIGATE THE PROBLEM
    
    //thread::sleep(Duration::from_millis(30_000));
    //b.broadcast(0);
    loop {
        thread::sleep(Duration::from_millis(100));
        //b.broadcast(1);
    }
}
```

There seems to be a leak on the receiving end (rx) that occurs when the bus is idle. Frequent usage of the bus helps mitigate the issue, but, in my tests, did not resolve it completely. On my system, the example above is allocating memory at a rate of about 2 MB/s.

System is running Ubuntu, kernel 4.8.0, x86_64. I was also able to reproduce the problem on my dev environment (macOS 10.12.6).

**Comment by jonhoo** [comment]
Ah, interesting.. Good catch! I believe this is because we use `park_timeout` (and have to) when we block, and so the channel send at https://github.com/jonhoo/bus/blob/master/src/lib.rs#L634 keeps getting re-executed. The right thing to do is likely to run that send only the first time `sw.spin()` returns false, and not on subsequent iterations. The `park_timeout` should ensure that any eventual message do get received, and the single send should mean that we still get woken up early in the majority of cases. Can you try that change and see if it fixes the leak you're observing?

**Comment by leovailati** [comment]
@jonhoo 

That fixed the problem, yes! I've ran the tests and it seems to be all ok.

```rust
        let mut first = true;
        loop {
            ...

            // park and tell writer to notify on write
            if first {
                if let Err(..) = self.waiting.send((thread::current(), self.head)) {
                    // writer has gone away, but this is not a reliable way to check
                    // in particular, we may also have missed updates
                    unimplemented!();
                }
                first = false;
            }
            ....
```

There is probably a better way to go about implementing this, but I am too sleepy to think about it right now. If you like this, I can open a PR.

**Comment by jonhoo** [comment]
That's basically the change I was thinking of, so I'd be happy to take it as a PR :)
