### ISSUE TITLE
Should BusReader require `T: Sync`?

### ISSUE THREAD

**Issue by stjepang** [jonhoo/bus#13]
I could be misunderstanding something, but it looks like multiple `BusReader`s could be attempting to receive a message and cloning the same element at the same time from different threads. Therefore, we must require `T: Sync`, but the bound is not present in the API.

Here's an example that demonstrates undefined behavior due to the lack of `T: Sync` bound:

```rust
extern crate bus;

use std::cell::Cell;
use std::thread;

use bus::Bus;

struct Foo(Cell<i32>);

impl Clone for Foo {
    fn clone(&self) -> Foo {
        println!("Cloning");
        thread::sleep_ms(1000);
        println!("Cloned");
        Foo(self.0.clone())
    }
}

fn main() {
    let mut bus = Bus::new(100);

    let mut rx1 = bus.add_rx();
    let mut rx2 = bus.add_rx();
    bus.broadcast(Foo(Cell::new(0)));

    let t1 = thread::spawn(move || {
        rx1.recv().unwrap();
    });

    let t2 = thread::spawn(move || {
        rx2.recv().unwrap();
    });

    t1.join().unwrap();
    t2.join().unwrap();
}
```

Output:

```
Cloning
Cloning
Cloned
Cloned
```

Looks like `Foo` is concurrently accessed from two threads even though it contains a `Cell<u32>`.

**Comment by jonhoo** [comment]
You are completely right! Fixed and released in 1.4.0. Thanks!
