### ISSUE TITLE
async feature's Stream implementation violates contract

### ISSUE THREAD

**Issue by benhansenslc** [jonhoo/bus#14]
Note that BusReader's futures::Stream implementation does not satisfy the Stream contract.  

> If NotReady is returned then this stream's next value is not ready yet and implementations will ensure that the current task will be notified when the next value may be ready. - [futures::Stream.poll](https://docs.rs/futures/0.1.21/futures/stream/trait.Stream.html#tymethod.poll)

Currently NotReady is returned without notifying the current task.  This causes receivers to hang forever even after new messages are broadcasted.

Perhaps this implementation should be removed until it is fixed/replaced or a warning should be put in the README.

Thanks for your work on this library.

**Comment by jonhoo** [comment]
You are completely right! Removed in the newly published 2.0.0.
