### ISSUE TITLE
Test it_iterates panics if ran in a loop

### ISSUE THREAD

**Issue by lespea** [jonhoo/bus#17]
I'm investigating a (possibly related?) issue where none of the receivers get any broadcasted items, unfortunately it only happens every so often and has been very frustrating to try and track down.  While trying to reproduce in the tests I changed it_iterates() to this:

```
#[test]
fn it_iterates() {
    for _ in 0..10_000 {
        use std::thread;

        let mut tx = bus::Bus::new(2);
        let mut rx = tx.add_rx();
        let j = thread::spawn(move || {
            for i in 0..1000 {
                tx.broadcast(i);
            }
        });

        let mut ii = 0;
        for i in rx.iter() {
            assert_eq!(i, ii);
            ii += 1;
        }

        j.join().unwrap();
        assert_eq!(ii, 1000);
        assert_eq!(rx.try_recv(), Err(mpsc::TryRecvError::Disconnected));
    }
}
```

and it will panic most times (not every time) with this:

```
running 1 test
test it_iterates ... FAILED

failures:

---- it_iterates stdout ----
thread 'it_iterates' panicked at 'not yet implemented', src/lib.rs:642:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: <bus::BusReader<T>>::recv_inner
   7: core::ops::function::FnOnce::call_once
   8: <F as alloc::boxed::FnBox<A>>::call_box
   9: __rust_maybe_catch_panic
  10: test::run_test::run_test_inner::{{closure}}


failures:
    it_iterates
```

This happens on a mac running mojave if that matters.  I still can't reliable reproduce the issue where the receivers never get any broadcast but if I can I'll open a separate issue.  Just figured I should mention it in case it's relevant to this.

**Comment by jonhoo** [comment]
I think this should be fixed in `2.1.0`, which I just released. Let me know if that's not the case!

**Comment by lespea** [comment]
Wow that was fast!  Tests are constantly passing on my machine and this also appears to have fixed the initial issue I was having.  Thank you so much!

**Comment by lespea** [comment]
Spoke to soon... it still occasionally happens that the receivers never get any of the messages and then it blocks forever on broadcast once the queue is full.
