### ISSUE TITLE
Problem with rand-core

### ISSUE THREAD

**Issue by kigafarz** [jonhoo/bus#20]
The Crate doesn't build anymore, the error:
the trait `rand_core::SeedableRng` is not implemented for `rand_hc::Hc128Rng`
the trait `rand_core::SeedableRng` is not implemented for `rand_xorshift::XorShiftRng`

It was fine before and no change has been made since

**Comment by jonhoo** [comment]
Ah, I've seen this happen for other crates too. Does a `cargo update` fix the issue for you?

**Comment by jonhoo** [comment]
Specifically, I believe this is related to https://github.com/rust-random/rand/issues/766

**Comment by kigafarz** [comment]
> Ah, I've seen this happen for other crates too. Does a `cargo update` fix the issue for you?
No, same problem with cargo update and then cargo build.

**Comment by jonhoo** [comment]
Actually, specifically, it is https://github.com/rust-random/rand/issues/818

**Comment by jonhoo** [comment]
This should be fixed with the new rand 0.7 release.
Also, note that `bus` does not itself depend on `rand`, so this issue is caused by some downstream dependency :)
