### ISSUE TITLE
Leaky version?

### ISSUE THREAD

**Issue by nazar-pc** [jonhoo/bus#31]
I have a use case that would benefit from a leaky version of the `Bus`, such that when number of messages reaches upper limit older messages are removed. I basically want to send messages from one place that may at some point be read at another place, but only last N really matter. Lock-free implementation would be really useful here.

**Comment by jonhoo** [comment]
I think in theory you could adapt that from the current implementation, but it would be a decently chunky difference from what's there today, so I don't think this makes sense to add to `bus` directly :)
