### ISSUE TITLE
BusReader stops receiving if another BusReader is dropped

### ISSUE THREAD

**Issue by lukebitts** [jonhoo/bus#4]
I have the following scenario: I have a `Bus` and two `BusReader`'s, The readers are sent to two different threads and they only `recv` a number of times each, the first `recvs` 5 times and the second `recvs` 10 times. The main thread then broadcasts with a 500ms interval between each broadcast. After the 5th broadcast, the first reader is dropped and its thread stops, the second one receives the 6th and 7th broadcast but then also stops, no error or panics, its like `recv` never returns.

I might be misunderstanding how this crate is suposed to work, I'm not very experienced with multithreading. This is the code that fails:

```rust
#![allow(deprecated)]
extern crate bus;

use std::thread;

fn main() {
	let mut bus = bus::Bus::new(1);

	let mut rx1 = bus.add_rx();
	let t1 = thread::spawn(move ||{
		for i in 0..5 {
			match rx1.recv() {
				Ok(v) => println!("T1: {} - {}", i, v),
				Err(e) => {
					println!("{}", e);
					break;
				}
			}
		}
		drop(rx1);
	});

	let mut rx2 = bus.add_rx();
	let t2 = thread::spawn(move ||{
		for i in 0..10 {
			match rx2.recv() {
				Ok(v) => println!("T2: {} - {}", i, v),
				Err(e) => {
					println!("{}", e);
					break;
				}
			}
		}
		drop(rx2);
	});

	std::thread::sleep_ms(500);

	for i in 0..25 {
		std::thread::sleep_ms(500);
		match bus.try_broadcast(i) {
			Ok(_) => println!("Broadcast successful"),
			Err(e) => println!("Broadcast failed {}", e)
		}
	}

	t1.join().unwrap();
	t2.join().unwrap();
}
```

Some observations:
* Increasing the `Bus` size only makes it take longer for `rx2` to stop `recv`ing. If the size is 1, it stops at the 7th broadcast, if it is 2, at the 9th, if its 3 at the 11th and so on.
* I don't mind losing some of the broadcasts due to the `Bus` being full, as long as `rx2` eventually receives the message.

This is the result of running the code on my machine:

```
T1: 0 - 0
T2: 0 - 0
Broadcast successful
T1: 1 - 1
T2: 1 - 1
Broadcast successful
T1: 2 - 2
T2: 2 - 2
Broadcast successful
T1: 3 - 3
T2: 3 - 3
Broadcast successful
T1: 4 - 4
T2: 4 - 4
Broadcast successful
T2: 5 - 5
Broadcast successful
T2: 6 - 6
Broadcast successful
Broadcast failed 7
Broadcast failed 8
Broadcast failed 9
Broadcast failed 10
[...]
Broadcast failed 24
```

**Comment by jonhoo** [comment]
Hmm, that's curious. Your code looks like it should work. I'll dig into it and report back.

**Comment by jonhoo** [comment]
Thanks for the report! That was definitely a serious bug.

**Comment by lukebitts** [comment]
Confirming it fixed my actual use case. Thanks :)
