### ISSUE TITLE
Can I cancel a recv after a timeout?

### ISSUE THREAD

**Issue by radix** [jonhoo/bus#8]
Hi. Thanks for the polished library!

I have threads dynamically creating BusReaders and recving on them, but I need to be able to stop these threads after a timeout. Is there a way to prevent bus from waiting forever if nothing is ever broadcast?

**Comment by jonhoo** [comment]
Released 1.2.0 which adds `recv_timeout` :)

**Comment by radix** [comment]
Wow, that's some great response time. My timeout wasn't even triggered! 😎

**Comment by jonhoo** [comment]
Note that this currently requires `beta` or `nightly`
